# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b0fbd30f6f44510bff1a7800bb26596e52505071b9a3813829142d1feb79e9c532b17302a9d64f4569f036b4bc668fd8b263c9425394496cb7d2fa390798d6c

test:
  secret_key_base: e2ec5e0458dcc9c94bea27060e4f2ad0243210e08011f7aafce86fa395547ee9b89027ad465293638fc1ca42e5bf4318bb242175600a046713bfdd820ae4d446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
